name: Check

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/check.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/check.yml"
  schedule:
    - cron: "0 0 * * *"

jobs:
  nonicons-font-check:
    name: Check nonicons-font
    runs-on: ubuntu-latest
    env:
      FOLDER: packages/nonicons-font
    outputs:
      diff: ${{ steps.diff.outputs.changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update checksum
        uses: datakrama/archlinux-package-action@v1
        with:
          path: "${{ env.FOLDER }}"
          namcap: false
          updpkgsums: true
          flags: ""

      - name: Git diff
        id: diff
        run: |
          if git diff --quiet ${{ env.FOLDER }}/PKGBUILD; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

  nonicons-font-update:
    name: Update nonicons-font
    runs-on: ubuntu-latest
    needs: nonicons-font-check
    if: needs.nonicons-font-check.outputs.diff == 'true'
    env:
      FOLDER: packages/nonicons-font

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: get-version
        run: |
          cd ${{ env.FOLDER }}
          git clone https://github.com/yamatsum/nonicons.git && cd nonicons
          echo "::set-output name=version::$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")"

      - name: Update PKGBUILD
        uses: datakrama/archlinux-package-action@v1
        with:
          path: "${{ env.FOLDER }}"
          pkgver: ${{ steps.get-version.outputs.version }}
          pkgrel: 1
          srcinfo: true
          flags: ""

      - name: Commit files
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.FOLDER }}/PKGBUILD ${{ env.FOLDER }}/.SRCINFO
          git commit -m "chore(nonicons-font): bump to ${{ steps.get-version.outputs.version }}"

      - name: Push changes
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger CI workflow
        if: github.event_name != 'pull_request'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI - nonicons-font
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "version": "${{ steps.get-version.outputs.version }}" }'

  docker-slim-bin-check:
    name: Check docker-slim-bin
    runs-on: ubuntu-latest
    env:
      FOLDER: packages/docker-slim-bin
    outputs:
      found: ${{ steps.search-version.outputs.found }}
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Get upstream version
        id: get-version
        run: echo "::set-output name=version::$(curl -s GET https://api.github.com/repos/docker-slim/docker-slim/tags | jq -r '.[].name' | head -n1)"

      - name: Find version on PKGBUILD
        id: search-version
        run: |
          cd ${{ env.FOLDER }}
          if grep -q "${{ steps.get-version.outputs.version }}" PKGBUILD
          then
            echo "::set-output name=found::true"
          else
            echo "::set-output name=found::false"
          fi

  docker-slim-bin-update:
    name: Update docker-slim-bin
    needs: docker-slim-bin-check
    if: needs.docker-slim-bin-check.outputs.found == 'false'
    runs-on: ubuntu-latest
    env:
      FOLDER: packages/docker-slim-bin

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update PKGBUILD
        uses: datakrama/archlinux-package-action@v1
        with:
          path: "${{ env.FOLDER }}"
          pkgver: ${{ needs.docker-slim-bin-check.outputs.version }}
          pkgrel: 1
          namcap: false
          updpkgsums: true
          srcinfo: true
          flags: ""

      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.FOLDER }}/PKGBUILD ${{ env.FOLDER }}/.SRCINFO
          git commit -m "chore(docker-slim-bin): bump to v${{ needs.docker-slim-bin-check.outputs.version }}"

      - name: Push changes
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger CI workflow
        if: github.event_name != 'pull_request'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI - docker-slim-bin
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "version": "${{ needs.docker-slim-bin-check.outputs.version }}" }'

  code-minimap-bin-check:
    name: Check code-minimap-bin
    runs-on: ubuntu-latest
    env:
      FOLDER: packages/code-minimap-bin
    outputs:
      found: ${{ steps.search-version.outputs.found }}
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Get upstream version
        id: get-version
        run: echo "::set-output name=version::$(curl --silent "https://api.github.com/repos/wfxr/code-minimap/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)"

      - name: Find version on PKGBUILD
        id: search-version
        run: |
          cd ${{ env.FOLDER }}
          if grep -q "${{ steps.get-version.outputs.version }}" PKGBUILD
          then
            echo "::set-output name=found::true"
          else
            echo "::set-output name=found::false"
          fi

  code-minimap-bin-update:
    name: Update code-minimap-bin
    needs: code-minimap-bin-check
    if: needs.code-minimap-bin-check.outputs.found == 'false'
    runs-on: ubuntu-latest
    env:
      FOLDER: packages/code-minimap-bin

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update PKGBUILD
        uses: datakrama/archlinux-package-action@v1
        with:
          path: "${{ env.FOLDER }}"
          pkgver: ${{ needs.code-minimap-bin-check.outputs.version }}
          pkgrel: 1
          namcap: false
          updpkgsums: true
          srcinfo: true
          flags: ""

      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.FOLDER }}/PKGBUILD ${{ env.FOLDER }}/.SRCINFO
          git commit -m "chore(code-minimap-bin): bump to v${{ needs.code-minimap-bin-check.outputs.version }}"

      - name: Push changes
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger CI workflow
        if: github.event_name != 'pull_request'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CI - code-minimap-bin
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "version": "${{ needs.code-minimap-bin-check.outputs.version }}" }'
